### ISSUE TITLE
Bitrot is not reading full file contents

### ISSUE THREAD

**Issue by Suicidal-Insanity** [ambv/bitrot#13]
After trying to figure out why this script was so much faster than expected, I stepped through the code and determined that all files are being opened and read in text mode. This means that the data which is being hashed for any given binary file is randomly truncated after a 0x1A byte, making the entire exercise moot.

This may be fixed by changing the open command to use 'rb' mode.

Unfortunately fixing this means that lots and lots of checksums will become invalid.

Example with added debug output:
>dir
  39 blah - Copy (2).dat
   3 blah - Copy (3) - Copy.dat
   3 blah - Copy (3).dat
 112 blah - Copy.dat
  11 blah.dat

> python.exe -m bitrot --verbose
       .\blah - Copy (2).dat; Length:            0; Checksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
.\blah - Copy (3) - Copy.dat; Length:            1; Checksum: 5ba93c9db0cff93f52b521d7420e43f6eda2784f
       .\blah - Copy (3).dat; Length:            1; Checksum: 5ba93c9db0cff93f52b521d7420e43f6eda2784f
           .\blah - Copy.dat; Length:            0; Checksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
                  .\blah.dat; Length:           11; Checksum: 3a4d8abb5811f6b58b9755ca65ffc01d38f9153f

Note multiple duplicate checksums.

With binary read mode:
> python.exe -m bitrot --verbose
File:          .\blah - Copy (2).dat; Length:           39; Checksum: ddfb5399fc8f39f26e43f7e3807ae919ee88fe59
File:   .\blah - Copy (3) - Copy.dat; Length:            3; Checksum: 4684f40f78d7474c93464241cf4a1ccaa012d7d3
File:          .\blah - Copy (3).dat; Length:            3; Checksum: edf5298c70ff205a98c17fd199ddd610e9e2c7c6
File:              .\blah - Copy.dat; Length:          112; Checksum: 733fdb8b5cc69814ff448b87af8b02681a749907
File:                     .\blah.dat; Length:           11; Checksum: 3a4d8abb5811f6b58b9755ca65ffc01d38f9153f

**Comment by ambv** [comment]
What system is that under?

**Comment by Suicidal-Insanity** [comment]
go ahead and just fix it - I don't have git setup on this PC.
