### ISSUE TITLE
Consider keeping hashsums in xattrs, rather than in SQLite?

### ISSUE THREAD

**Issue by ghost** [ambv/bitrot#49]
It seems that the need for an external state storage can be reduced if the most recent scan date, as well as the hash, is kept in xattrs.

**Comment by juanep97** [comment]
I think the current centralized sqlite file allows for easier managing (moving a folder and its file together), and makes it independent of the underlying filesystem (moving files or backups between disks and operating systems). Also, it does not affect the file itself.
